version: '3.8'

services:
  app:
    build: .
    container_name: php_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php -S 0.0.0.0:8000 -t src
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/dbname"
    entrypoint: ["/var/www/docker/entrypoint.sh"]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
